### ISSUE TITLE
Custom image dataset with two classes

### ISSUE THREAD

**Issue by selcukyazarklu** [Indoxer/LKAN#1]
Hi,
how can I apply image classification with two classes set like 64* 64 images ? I try to implement mint sample in kaggle

**Comment by Indoxer** [comment]
I am not sure if I understand but, KANLinear, KANLinearFFT, KANConv2d, are almost the same in usage as nn.Linear and nn.Conv2D, you can just import them and create your own model, see test_conv.py. You can just create models with them. But memory usage can be issue, when I write versions for cuda to boost performance and avoid memory issue, I will make a tutorial on how to use configs, trainers, etc.

**Comment by Indoxer** [comment]
Oh sorry, I broke Conv2d, when I made placeholder for cuda version, try to pull new changes

**Comment by selcukyazarklu** [comment]
Hi, thank you for quick response. your work is really great. by the way, I converted my images 28x28 single channel :), and tried simple mnist model with default configs. ( edited basic.yaml, Testdataloader etc.) and this time it gives a " fftkan() missing 1 required positional argument: 'G'" error. I will wait the tutorials. Regards.

**Comment by Indoxer** [comment]
> Oh sorry, I broke Conv2d, when I made placeholder for cuda version, try to pull new changes

This is reason, now should everything works

**Comment by selcukyazarklu** [comment]
Ok, it Works!. thank you.
